[package]
name = "lemon_pdf_derive"
version = "0.1.0"
authors = ["Manuel Reinhardt <manuel.rhdt@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.29"
quote = "0.6.11"
proc-macro2 = "0.4.27"
Inflector = "0.11.4"
